### ISSUE TITLE
Implement automatic updates

### ISSUE THREAD

**Issue by MOSjens** [cryptocatalog/ultimate-crypto-comparison#11]
Implement the automatic updates of the meta information of the libraries

**Comment by kmindi** [comment]
Propose a draft how you want to implement this.

**Comment by schneisn** [comment]
Is implemented in #19. The git-scrabber searches for information of libraries that have a valid url specified in the markdown file. Afterwards, the information from the report is added to the libraries. If an information (e.g. the used block ciphers of a library) is specified in the markdown, this data is prefered over the collected data.
