### ISSUE TITLE
use attributes of actual libraries for demo purposes

### ISSUE THREAD

**Issue by kmindi** [cryptocatalog/ultimate-crypto-comparison#13]

**Comment by kmindi** [comment]
How is this fixed by 6f92031

**Comment by schneisn** [comment]
Same issue as in described in https://github.com/CryptoCatalog/ultimate-crypto-comparison/issues/14.  
But is actually included in #17. In this MR I added filters and information for the libraries.  
I got the information from the report of the master fachstudie.
