### ISSUE TITLE
Integration of Security/Vulnerabilities trackers

### ISSUE THREAD

**Issue by MOSjens** [cryptocatalog/ultimate-crypto-comparison#2]
For automatic updates of the informatuon about the libraries, it would be handy to include also other information from public vulnerability databases and trackers. This improves the list that with this addition not only shows if there are recent updates to the library (active devdlopment) but also how many or which vulnerabilities are not fixed in the library.
For example: https://www.cvedetails.com/

**Comment by schneisn** [comment]
Added in c0b2508d7425eda24cbd26d27daa7965c6b9bec9
