### ISSUE TITLE
Different versions of a library

### ISSUE THREAD

**Issue by MOSjens** [cryptocatalog/ultimate-crypto-comparison#3]
Many libraries have different branches/versions/variants that differ in their release status/support status/development status.

It must be shown which version the information is about.

And other versions of a library should also be possible to be listed/compared.

**Comment by schneisn** [comment]
To show which information belongs to which version(s) of a library, we could introduce a tag next to the name of the library. This tag contains the version number of the library. It can also contain the range of versions for which the information is valid.  
Having a seperate tag allows to compare different versions of  a library. On the other hand, every version of a library has its own entry in the catalog, but this is easier to realize than changing the details view of a library and include some kind of versioning.

**Comment by schneisn** [comment]
#17 includes a field called "Release". This release tag shows which release (version) the data of the library entry is applicable to.
