### ISSUE TITLE
Empty CVE Details suggest there are no CVEs

### ISSUE THREAD

**Issue by kmindi** [cryptocatalog/ultimate-crypto-comparison#34]
If CVE Details can not be fetched, because vendor/product.. was not specified, there should be a message indicating that it has not been connected or similar. Otherwise one could assume there are no CVEs.

**Comment by schneisn** [comment]
There is now a text if no product/vendor is specified or if the API did not return any information about this library. (eb3e6502f86379166f528e83f247f9a829a429e1)
