### ISSUE TITLE
Threshold for including encryptions

### ISSUE THREAD

**Issue by schneisn** [cryptocatalog/ultimate-crypto-comparison#38]
@kmindi 
What is an appropriate threshold for the number of occurences of an encryption for it to be shown in a library? I have looked in the "Classificiation of cryptographic libraries" but havent found any specific number.

**Comment by kmindi** [comment]
Maybe `3`? Let's try it with `3`

**Comment by schneisn** [comment]
I changed it to 3. I'm going to compare our results with the results of the classification. Hopefully theirs are correct.

**Comment by schneisn** [comment]
@kmindi The threshold in the classification of cryptographic libraries seems to be lower than 3. However, I would stay with a threshold of 3 because I think otherwise the catalog shows many false positives.

**Comment by kmindi** [comment]
Okay, that's fine.
