### ISSUE TITLE
Fix Error with filter

### ISSUE THREAD

**Issue by MOSjens** [cryptocatalog/ultimate-crypto-comparison#8]
Fix the Error in the framework with the filter.

**Comment by schneisn** [comment]
Waiting for fix in https://github.com/ultimate-comparisons/ultimate-comparison-BASE

**Comment by schneisn** [comment]
Filtering works now for columns that are specified in all markdown files. The remaining bug is reported an will be fixed in the framework

**Comment by schneisn** [comment]
Fixed in 081a318e29a5ad5a6a99b5214a8f67e95c1278da
