### ISSUE TITLE
create a new design 

### ISSUE THREAD

**Issue by MOSjens** [cryptocatalog/ultimate-crypto-comparison#9]
create a new design which includes the framework and the automatic updates.

**Comment by MOSjens** [comment]
![20180205_122124](https://user-images.githubusercontent.com/34648729/35864881-4ffb9248-0b53-11e8-9e42-ea19a903c33e.jpg)

**Comment by schneisn** [comment]
Can you capture this with a uml tool and add it to the internal repo? Would be nice to have this for the documentation and the report

**Comment by schneisn** [comment]
Is this done?

**Comment by MOSjens** [comment]
Yes it is. it can be found here:
https://gilbert.informatik.uni-stuttgart.de/minderki/online-catalog-of-cryptographic-libraries/tree/master/project_documentation/design
